version: 0.0
os: linux
files:
  - source: target/*.java
    destination: ~/javaapp/
hooks:
  AfterInstall:
    # - location: scripts/install_dependencies.sh
    #   timeout: 300
    #   runas: root
    # - location: scripts/codestar_remote_access
    #   timeout: 300
    #   runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
