version: 0.2

phases:
  install:
    commands:
      # Use Open JDK 8
      # Source https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04
      - apt-get install -y awscli git htop maven openjdk-8-jdk vim
      - which java
      - java -version
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn package -e -X
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      # - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  type: zip
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
    - 'template-configuration.json'
